name: Generate PDF CI

on:
  push:
    branches: "main" 
    paths: ['src/**', 'Resume.tex']
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Latest Code
        uses: actions/checkout@v4

      - name: Build PDF using abrahamvg/resume-gen
        uses: addnab/docker-run-action@v3
        with:
            image: abrahamvg/resume-gen
            options: -v ${{ github.workspace }}:/data abrahamvg/resume-gen Resume.tex

      - name: Move file to static folder
        run: |
          mkdir static 2>/dev/null || echo "Error creating directory 'static': $?"
          mv Resume.pdf static
          
      - name: Publish Resume
        uses: stefanzweifel/git-auto-commit-action@v4.9.2
        with:
          commit_message: ":page_facing_up: Resume Update"